### ISSUE TITLE
Use case for limiting calls to reset password

### ISSUE THREAD

**Issue by alexisjcarr** [alexisjcarr/macrolimiter#1]
#### Description

We need a quick and dirty fullstack app: a React client with a login form with a reset password button, and an Express server with macrolimiter implemented. 

Calls to reset password should be limited to 2 per day.

#### Files

examples/

#### Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.

- [ ] Create React client with a login form with a reset password button
- [ ] Create an Express server with macrolimiter implemented and a reset password route
- [ ] Calls to reset password should be limited to 2 per day
