### ISSUE TITLE
Add in fixed window functionality

### ISSUE THREAD

**Issue by alexisjcarr** [alexisjcarr/macrolimiter#2]
#### Description

Add in the ability for `keyLimiter()` to handle time inputs. 

#### Files

modules/keyLimiter
redis/

#### Tasks

- [ ] Implement clock.js and worker.js by adding files to redis folder and a Procfile.
- [ ] implement the `cron` package instead of `node-cron`.
- [ ] Test on Heroku.
- [ ] Research whether or not this is a general solution.
