### ISSUE TITLE
Testing, tying to Travis, and adding build passing/failing badge

### ISSUE THREAD

**Issue by alexisjcarr** [alexisjcarr/macrolimiter#3]
#### Description

Testing, tying to Travis CI, and adding build passing/failing to docs.

#### Files

__tests__/
README.md

#### Tasks

- [ ] Write tests for each of the modules
- [ ] Hook up to Travis CI, and
- [ ] Copy/paste build passing/failing in README.md
